version: "3"
services: 
  postgresql:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin
